<?php

return [
    [
        'code' => 'USD',
        'name' => 'US Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'EUR',
        'name' => 'Euro',
        'symbol' => '€',
        'scale' => 2,
    ],
    [
        'code' => 'GBP',
        'name' => 'Pound Sterling',
        'symbol' => '£',
        'scale' => 2,
    ],
    [
        'code' => 'INR',
        'name' => 'Indian Rupee',
        'symbol' => '₹',
        'scale' => 2,
    ],
    [
        'code' => 'AED',
        'name' => 'UAE Dirham',
        'symbol' => 'دإ‏',
        'scale' => 2,
    ],
    [
        'code' => 'AFN',
        'name' => 'Afghani',
        'symbol' => '؋',
        'scale' => 2,
    ],
    [
        'code' => 'ALL',
        'name' => 'Lek',
        'symbol' => 'Lek',
        'scale' => 2,
    ],
    [
        'code' => 'AMD',
        'name' => 'Armenian Dram',
        'symbol' => 'դր.',
        'scale' => 2,
    ],
    [
        'code' => 'ANG',
        'name' => 'Netherlands Antillian Guilder',
        'symbol' => 'ƒ',
        'scale' => 2,
    ],
    [
        'code' => 'AOA',
        'name' => 'Kwanza',
        'symbol' => 'Kz',
        'scale' => 2,
    ],
    [
        'code' => 'ARS',
        'name' => 'Argentine Peso',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'AUD',
        'name' => 'Australian Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'AWG',
        'name' => 'Aruban Guilder',
        'symbol' => 'ƒ',
        'scale' => 2,
    ],
    [
        'code' => 'AZN',
        'name' => 'Azerbaijanian Manat',
        'symbol' => '₼',
        'scale' => 2,
    ],
    [
        'code' => 'BAM',
        'name' => 'Convertible Marks',
        'symbol' => 'КМ',
        'scale' => 2,
    ],
    [
        'code' => 'BBD',
        'name' => 'Barbados Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'BDT',
        'name' => 'Taka',
        'symbol' => '৳',
        'scale' => 2,
    ],
    [
        'code' => 'BGN',
        'name' => 'Bulgarian Lev',
        'symbol' => 'лв.',
        'scale' => 2,
    ],
    [
        'code' => 'BHD',
        'name' => 'Bahraini Dinar',
        'symbol' => '.د.',
        'scale' => 3,
    ],
    [
        'code' => 'BIF',
        'name' => 'Burundi Franc',
        'symbol' => 'FBu',
        'scale' => 0,
    ],
    [
        'code' => 'BMD',
        'name' => 'Bermudian Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'BND',
        'name' => 'Brunei Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'BOB',
        'name' => 'Boliviano',
        'symbol' => 'Bs',
        'scale' => 2,
    ],
    [
        'code' => 'BRL',
        'name' => 'Brazilian Real',
        'symbol' => 'R$',
        'scale' => 2,
    ],
    [
        'code' => 'BSD',
        'name' => 'Bahamian Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'BTN',
        'name' => 'Ngultrum',
        'symbol' => 'Nu.',
        'scale' => 2,
    ],
    [
        'code' => 'BWP',
        'name' => 'Pula',
        'symbol' => 'P',
        'scale' => 2,
    ],
    [
        'code' => 'BYN',
        'name' => 'Belarusian Ruble',
        'symbol' => 'р.',
        'scale' => 2,
    ],
    [
        'code' => 'BZD',
        'name' => 'Belize Dollar',
        'symbol' => 'BZ$',
        'scale' => 2,
    ],
    [
        'code' => 'CAD',
        'name' => 'Canadian Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'CDF',
        'name' => 'Congolese Franc',
        'symbol' => 'FC',
        'scale' => 2,
    ],
    [
        'code' => 'CHF',
        'name' => 'Swiss Franc',
        'symbol' => 'CHF',
        'scale' => 2,
    ],
    [
        'code' => 'CLP',
        'name' => 'Chilean Peso',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'CNY',
        'name' => 'Yuan Renminbi',
        'symbol' => '¥',
        'scale' => 2,
    ],
    [
        'code' => 'COP',
        'name' => 'Colombian Peso',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'CRC',
        'name' => 'Costa Rican Colon',
        'symbol' => '₡',
        'scale' => 2,
    ],
    [
        'code' => 'CUC',
        'name' => 'Cuban Convertible Peso',
        'symbol' => 'CUC',
        'scale' => 2,
    ],
    [
        'code' => 'CUP',
        'name' => 'Cuban Peso',
        'symbol' => '$MN',
        'scale' => 2,
    ],
    [
        'code' => 'CVE',
        'name' => 'Cape Verde Escudo',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'CZK',
        'name' => 'Czech Koruna',
        'symbol' => 'Kč',
        'scale' => 2,
    ],
    [
        'code' => 'DJF',
        'name' => 'Djibouti Franc',
        'symbol' => 'Fdj',
        'scale' => 0,
    ],
    [
        'code' => 'DKK',
        'name' => 'Danish Krone',
        'symbol' => 'kr.',
        'scale' => 2,
    ],
    [
        'code' => 'DOP',
        'name' => 'Dominican Peso',
        'symbol' => 'RD$',
        'scale' => 2,
    ],
    [
        'code' => 'DZD',
        'name' => 'Algerian Dinar',
        'symbol' => 'د.ج‏',
        'scale' => 2,
    ],
    [
        'code' => 'EGP',
        'name' => 'Egyptian Pound',
        'symbol' => 'ج.م',
        'scale' => 2,
    ],
    [
        'code' => 'ERN',
        'name' => 'Nakfa',
        'symbol' => 'Nfk',
        'scale' => 2,
    ],
    [
        'code' => 'ETB',
        'name' => 'Ethiopian Birr',
        'symbol' => 'ETB',
        'scale' => 2,
    ],
    [
        'code' => 'FJD',
        'name' => 'Fiji Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'FKP',
        'name' => 'Falkland Islands Pound',
        'symbol' => '£',
        'scale' => 2,
    ],
    [
        'code' => 'GEL',
        'name' => 'Lari',
        'symbol' => 'ლ',
        'scale' => 2,
    ],
    [
        'code' => 'GHS',
        'name' => 'Ghana Cedi',
        'symbol' => '₵',
        'scale' => 2,
    ],
    [
        'code' => 'GIP',
        'name' => 'Gibraltar Pound',
        'symbol' => '£',
        'scale' => 2,
    ],
    [
        'code' => 'GMD',
        'name' => 'Dalasi',
        'symbol' => 'D',
        'scale' => 2,
    ],
    [
        'code' => 'GTQ',
        'name' => 'Quetzal',
        'symbol' => 'Q',
        'scale' => 2,
    ],
    [
        'code' => 'GYD',
        'name' => 'Guyana Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'HKD',
        'name' => 'Hong Kong Dollar',
        'symbol' => 'HK$',
        'scale' => 2,
    ],
    [
        'code' => 'HNL',
        'name' => 'Lempira',
        'symbol' => 'L.',
        'scale' => 2,
    ],
    [
        'code' => 'HRK',
        'name' => 'Croatian Kuna',
        'symbol' => 'kn',
        'scale' => 2,
    ],
    [
        'code' => 'HTG',
        'name' => 'Gourde',
        'symbol' => 'G',
        'scale' => 2,
    ],
    [
        'code' => 'HUF',
        'name' => 'Forint',
        'symbol' => 'Ft',
        'scale' => 2,
    ],
    [
        'code' => 'IDR',
        'name' => 'Rupiah',
        'symbol' => 'Rp',
        'scale' => 0,
    ],
    [
        'code' => 'ILS',
        'name' => 'New Israeli Shekel',
        'symbol' => '₪',
        'scale' => 2,
    ],
    [
        'code' => 'IQD',
        'name' => 'Iraqi Dinar',
        'symbol' => 'د.ع.‏',
        'scale' => 2,
    ],
    [
        'code' => 'IRR',
        'name' => 'Iranian Rial',
        'symbol' => '﷼',
        'scale' => 2,
    ],
    [
        'code' => 'ISK',
        'name' => 'Iceland Krona',
        'symbol' => 'kr.',
        'scale' => 0,
    ],
    [
        'code' => 'JMD',
        'name' => 'Jamaican Dollar',
        'symbol' => 'J$',
        'scale' => 2,
    ],
    [
        'code' => 'JOD',
        'name' => 'Jordanian Dinar',
        'symbol' => 'د.ا.‏',
        'scale' => 3,
    ],
    [
        'code' => 'JPY',
        'name' => 'Yen',
        'symbol' => '¥',
        'scale' => 0,
    ],
    [
        'code' => 'KES',
        'name' => 'Kenyan Shilling',
        'symbol' => 'S',
        'scale' => 2,
    ],
    [
        'code' => 'KGS',
        'name' => 'Som',
        'symbol' => 'сом',
        'scale' => 2,
    ],
    [
        'code' => 'KHR',
        'name' => 'Riel',
        'symbol' => '៛',
        'scale' => 0,
    ],
    [
        'code' => 'KMF',
        'name' => 'Comoro Franc',
        'symbol' => 'CF',
        'scale' => 2,
    ],
    [
        'code' => 'KPW',
        'name' => 'North Korean Won',
        'symbol' => '₩',
        'scale' => 2,
    ],
    [
        'code' => 'KRW',
        'name' => 'Won',
        'symbol' => '₩',
        'scale' => 0,
    ],
    [
        'code' => 'KWD',
        'name' => 'Kuwaiti Dinar',
        'symbol' => 'دينار‎‎‏',
        'scale' => 3,
    ],
    [
        'code' => 'KYD',
        'name' => 'Cayman Islands Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'KZT',
        'name' => 'Tenge',
        'symbol' => '₸',
        'scale' => 2,
    ],
    [
        'code' => 'LAK',
        'name' => 'Kip',
        'symbol' => '₭',
        'scale' => 0,
    ],
    [
        'code' => 'LBP',
        'name' => 'Lebanese Pound',
        'symbol' => 'ل.ل.‏',
        'scale' => 2,
    ],
    [
        'code' => 'LKR',
        'name' => 'Sri Lanka Rupee',
        'symbol' => '₨',
        'scale' => 2,
    ],
    [
        'code' => 'LRD',
        'name' => 'Liberian Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'LSL',
        'name' => 'Loti',
        'symbol' => 'M',
        'scale' => 2,
    ],
    [
        'code' => 'LYD',
        'name' => 'Libyan Dinar',
        'symbol' => 'ل.د',
        'scale' => 3,
    ],
    [
        'code' => 'MAD',
        'name' => 'Moroccan Dirham',
        'symbol' => 'د.م.',
        'scale' => 2,
    ],
    [
        'code' => 'MDL',
        'name' => 'Moldovan Leu',
        'symbol' => 'lei',
        'scale' => 2,
    ],
    [
        'code' => 'MGA',
        'name' => 'Malagasy Ariary',
        'symbol' => 'Ar',
        'scale' => 2,
    ],
    [
        'code' => 'MKD',
        'name' => 'Denar',
        'symbol' => 'ден.',
        'scale' => 2,
    ],
    [
        'code' => 'MMK',
        'name' => 'Kyat',
        'symbol' => 'K',
        'scale' => 2,
    ],
    [
        'code' => 'MNT',
        'name' => 'Tugrik',
        'symbol' => '₮',
        'scale' => 2,
    ],
    [
        'code' => 'MOP',
        'name' => 'Pataca',
        'symbol' => 'MOP$',
        'scale' => 2,
    ],
    [
        'code' => 'MRO',
        'name' => 'Ouguiya',
        'symbol' => 'UM',
        'scale' => 2,
    ],
    [
        'code' => 'MUR',
        'name' => 'Mauritius Rupee',
        'symbol' => '₨',
        'scale' => 2,
    ],
    [
        'code' => 'MVR',
        'name' => 'Rufiyaa',
        'symbol' => 'MVR',
        'scale' => 2,
    ],
    [
        'code' => 'MWK',
        'name' => 'Kwacha',
        'symbol' => 'MK',
        'scale' => 2,
    ],
    [
        'code' => 'MXN',
        'name' => 'Mexican Peso',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'MYR',
        'name' => 'Malaysian Ringgit',
        'symbol' => 'RM',
        'scale' => 2,
    ],
    [
        'code' => 'MZN',
        'name' => 'Mozambique Metical',
        'symbol' => 'MT',
        'scale' => 2,
    ],
    [
        'code' => 'NAD',
        'name' => 'Namibian Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'NGN',
        'name' => 'Naira',
        'symbol' => '₦',
        'scale' => 2,
    ],
    [
        'code' => 'NIO',
        'name' => 'Cordoba Oro',
        'symbol' => 'C$',
        'scale' => 2,
    ],
    [
        'code' => 'NOK',
        'name' => 'Norwegian Krone',
        'symbol' => 'kr',
        'scale' => 2,
    ],
    [
        'code' => 'NPR',
        'name' => 'Nepalese Rupee',
        'symbol' => '₨',
        'scale' => 2,
    ],
    [
        'code' => 'NZD',
        'name' => 'New Zealand Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'OMR',
        'name' => 'Rial Omani',
        'symbol' => '﷼',
        'scale' => 3,
    ],
    [
        'code' => 'PAB',
        'name' => 'Balboa',
        'symbol' => 'B/.',
        'scale' => 2,
    ],
    [
        'code' => 'PEN',
        'name' => 'Nuevo Sol',
        'symbol' => 'S/.',
        'scale' => 2,
    ],
    [
        'code' => 'PGK',
        'name' => 'Kina',
        'symbol' => 'K',
        'scale' => 2,
    ],
    [
        'code' => 'PHP',
        'name' => 'Philippine Peso',
        'symbol' => '₱',
        'scale' => 2,
    ],
    [
        'code' => 'PKR',
        'name' => 'Pakistan Rupee',
        'symbol' => '₨',
        'scale' => 2,
    ],
    [
        'code' => 'PLN',
        'name' => 'Poland, Zloty',
        'symbol' => 'zł',
        'scale' => 2,
    ],
    [
        'code' => 'PYG',
        'name' => 'Guarani',
        'symbol' => '₲',
        'scale' => 2,
    ],
    [
        'code' => 'QAR',
        'name' => 'Qatari Rial',
        'symbol' => 'ر.ق',
        'scale' => 2,
    ],
    [
        'code' => 'RON',
        'name' => 'New Romanian Leu',
        'symbol' => 'lei',
        'scale' => 2,
    ],
    [
        'code' => 'RSD',
        'name' => 'Serbian Dinar',
        'symbol' => 'Дин.',
        'scale' => 2,
    ],
    [
        'code' => 'RUB',
        'name' => 'Russian Ruble',
        'symbol' => '₽',
        'scale' => 2,
    ],
    [
        'code' => 'RWF',
        'name' => 'Rwanda Franc',
        'symbol' => 'RWF',
        'scale' => 2,
    ],
    [
        'code' => 'SAR',
        'name' => 'Saudi Riyal',
        'symbol' => '﷼',
        'scale' => 2,
    ],
    [
        'code' => 'SBD',
        'name' => 'Solomon Islands Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'SCR',
        'name' => 'Seychelles Rupee',
        'symbol' => '₨',
        'scale' => 2,
    ],
    [
        'code' => 'SDG',
        'name' => 'Sudanese Pound',
        'symbol' => 'SD',
        'scale' => 2,
    ],
    [
        'code' => 'SEK',
        'name' => 'Swedish Krona',
        'symbol' => 'kr',
        'scale' => 2,
    ],
    [
        'code' => 'SGD',
        'name' => 'Singapore Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'SHP',
        'name' => 'Saint Helena Pound',
        'symbol' => '£',
        'scale' => 2,
    ],
    [
        'code' => 'SLL',
        'name' => 'Leone',
        'symbol' => 'Le',
        'scale' => 2,
    ],
    [
        'code' => 'SOS',
        'name' => 'Somali Shilling',
        'symbol' => 'Sh',
        'scale' => 2,
    ],
    [
        'code' => 'SRD',
        'name' => 'Surinam Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'STD',
        'name' => 'Dobra',
        'symbol' => 'Db',
        'scale' => 2,
    ],
    [
        'code' => 'SVC',
        'name' => 'El Salvador Colon',
        'symbol' => '₡',
        'scale' => 2,
    ],
    [
        'code' => 'SYP',
        'name' => 'Syrian Pound',
        'symbol' => '£',
        'scale' => 2,
    ],
    [
        'code' => 'SZL',
        'name' => 'Lilangeni',
        'symbol' => 'E',
        'scale' => 2,
    ],
    [
        'code' => 'THB',
        'name' => 'Baht',
        'symbol' => '฿',
        'scale' => 2,
    ],
    [
        'code' => 'TJS',
        'name' => 'Somoni',
        'symbol' => 'TJS',
        'scale' => 2,
    ],
    [
        'code' => 'TMT',
        'name' => 'Turkmenistan Manat',
        'symbol' => 'm',
        'scale' => 2,
    ],
    [
        'code' => 'TND',
        'name' => 'Tunisian Dinar',
        'symbol' => 'د.ت‏',
        'scale' => 3,
    ],
    [
        'code' => 'TOP',
        'name' => 'Pa`anga',
        'symbol' => 'T$',
        'scale' => 2,
    ],
    [
        'code' => 'TRY',
        'name' => 'Turkish Lira',
        'symbol' => 'TL',
        'scale' => 2,
    ],
    [
        'code' => 'TTD',
        'name' => 'Trinidad and Tobago Dollar',
        'symbol' => 'TT$',
        'scale' => 2,
    ],
    [
        'code' => 'TWD',
        'name' => 'New Taiwan Dollar',
        'symbol' => 'NT$',
        'scale' => 2,
    ],
    [
        'code' => 'TZS',
        'name' => 'Tanzanian Shilling',
        'symbol' => 'Sh',
        'scale' => 2,
    ],
    [
        'code' => 'UAH',
        'name' => 'Hryvnia',
        'symbol' => '₴',
        'scale' => 2,
    ],
    [
        'code' => 'UGX',
        'name' => 'Uganda Shilling',
        'symbol' => 'USh',
        'scale' => 2,
    ],
    [
        'code' => 'UYU',
        'name' => 'Peso Uruguayo',
        'symbol' => '$U',
        'scale' => 2,
    ],
    [
        'code' => 'UZS',
        'name' => 'Uzbekistan Sum',
        'symbol' => 'сўм',
        'scale' => 2,
    ],
    [
        'code' => 'VEF',
        'name' => 'Bolivar',
        'symbol' => 'Bs.',
        'scale' => 2,
    ],
    [
        'code' => 'VND',
        'name' => 'Dong',
        'symbol' => '₫',
        'scale' => 0,
    ],
    [
        'code' => 'VUV',
        'name' => 'Vatu',
        'symbol' => 'VT',
        'scale' => 0,
    ],
    [
        'code' => 'WST',
        'name' => 'Tala',
        'symbol' => 'WS$',
        'scale' => 2,
    ],
    [
        'code' => 'XAF',
        'name' => 'Franc CFA (XAF)',
        'symbol' => 'F.CFA',
        'scale' => 2,
    ],
    [
        'code' => 'XCD',
        'name' => 'East Caribbean Dollar',
        'symbol' => '$',
        'scale' => 2,
    ],
    [
        'code' => 'XOF',
        'name' => 'Franc CFA (XOF)',
        'symbol' => 'F.CFA',
        'scale' => 2,
    ],
    [
        'code' => 'YER',
        'name' => 'Yemeni Rial',
        'symbol' => '﷼',
        'scale' => 2,
    ],
    [
        'code' => 'ZAR',
        'name' => 'Rand',
        'symbol' => 'R',
        'scale' => 2,
    ],
    [
        'code' => 'ZMW',
        'name' => 'Zambia Kwacha',
        'symbol' => 'ZK',
        'scale' => 2,
    ],
];
